### PR TITLE
add support for rpmbuild stages

### PR DESCRIPTION
**Pull request by wdpypere**
This allows people to use the plugin to make source rpms.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Can you explain in which scenario this would be useful? Since this wouldn't really allow building SRPM that you can build in the traditional sense.

**Comment by jrha** [comment]
@rickard-von-essen, it is not intended that the SRPMs would be used to rebuild (from source), but they would make repackaging much easier. We have some users who like to produce internal variants of our upstream packages. We would like to make this process easier for them without having to use our complete build environment.

**Comment by rickard-von-essen** [comment]
I'm a bit reluctant to add this feature since it slightly redefines the meaning of `srpm`.

**Comment by rickard-von-essen** [comment]
@dantran What's your view on this?

**Comment by dantran** [comment]
@rickard-von-essen i see no issue

**Comment by rickard-von-essen** [comment]
Ok, then we can merge this if you add some docs, unit tests and at least on It.

**Comment by wdpypere** [comment]
@rickard-von-essen I added some documentation and tests.

**Comment by rickard-von-essen** [comment]
LGTM

**Comment by wdpypere** [comment]
@rickard-von-essen I see there are preparations for a 2.2.0 release, would this be included? Thanks.

**Pull request merged**
