### PR TITLE
Allow for scriptlets and triggers to be filtered with properties.

### PR DESCRIPTION
**Pull request by chiknrice**
A new configuration property "filter" were added for scriptlets and
triggers.  The underlying implementation uses the default filter wrappers
available in the RPM mojo.

Both script or scriptFile can be filtered with standard maven filtering by setting the "filter" parameter to true:
```
                    <preinstallScriptlet>
                        <scriptFile>rpm/preInstall.sh</scriptFile>
                        <filter>true</filter>
                    </preinstallScriptlet>
```

### CODE REVIEW

**Comment by dantran** [comment]
Please add test and doc. Thanks for helping out

**Comment by chiknrice** [comment]
Added test and doc.

**Comment by chiknrice** [comment]
@dantran are my test & doc acceptable?

**Comment by chiknrice** [comment]
@dantran any news on my PR? thanks!

**Comment by rickard-von-essen** [comment]
LGTM 👍

**Comment by xandris** [comment]
this is super useful for us right now. when will 2.2.0 drop? 😄

**Pull request merged**
