### PR TITLE
Add support for the spec BuildRequires list of dependencies

### PR DESCRIPTION
**Pull request by mgumbley-resilient**
Hi,
We needed to have a build-time dependency on some RPM packages, so added support for the
<buildRequires>
  <buildRequire>our-special-build-tool</buildRequire>
</buildRequires>
configuration, that gets converted into BuildRequires: our-special-build-tool in the spec file.

Hope this is of use!
Kind regards, and thanks for the rpm-maven-plugin!

Matt

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Can you add some docs.

**Comment by mgumbley-resilient** [comment]
Thank you Rickard, I've added a section to the advanced parameters doc.
Regards,
Matt

**Comment by dantran** [comment]
@mgumbley-resilient Could you please resolve the current conflict.  Huge thanks

**Comment by rickard-von-essen** [comment]
@mgumbley-resilient If you rebase this I can merge it.

**Comment by mgumbley-resilient** [comment]
Hi Rickard & Dan, apologies for the delay in resolving these conflicts - the two files affected now contain the build-requires changes and the pre/post-requires changes.

**Comment by mgumbley-resilient** [comment]
Hi Rickard & Dan, is the project in a state to do a new release containing this PR, or are there other changes to be integrated before the next release?
Regards,
Matt

**Pull request merged**
